Decimal myBMI = Fitness.calculateBMI(90, 1.76);
System.debug(fitness.calculateBMI(90, 1.76).setScale(3) ); 


Decimal myPace = Fitness.calculatePace(15.5, 60);
System.debug(myPace); 


Pizza p1 = new Pizza('s',2,3);
System.debug('p1.totalCost() value is : ' + p1.totalCost());
System.debug('Your'+ p1.size +'size Pizza with ' + p1.numberOfCheeseTopping + 'and'+ p1.numberOfPepperoniTopping+p1.totalCost() );

