/* 
//Task7
Declare 3 Integer variavles and initialize their values. 
Write a code to print out the largest number by comparing them with each other. 
*/

integer num1 = 500;
integer num2 = 400;
integer num3 = 300;

if(num1 > num2 && num1 > num3 ){
    System.debug('Largest number ' + num1);
    
}else if(num2 > num3 && num2 > num1){
    System.debug('Largest number ' + num2);
}else if(num3 > num2 && num3 > num1){
    System.debug('Largest number ' + num3);
}
*/
